### ISSUE TITLE
Difficult to get download links

### ISSUE THREAD

**Issue by twerdster** [laMia482/caffe2_android#1]
The Baidu download links are unreachable / impossibly slow to download
probably because I am outside of China:
https://pan.baidu.com/s/1c8oopC
https://pan.baidu.com/s/1gfdBV2b

Any chance of uploading them to Amazon S3 or DropBox?

**Comment by laMia482** [comment]
@twerdster I upload to DropBox 
caffe2.tar https://www.dropbox.com/s/v0g9dzzdj364fox/caffe2.tar?dl=0
caffe2_prebuilt.tar https://www.dropbox.com/s/x2g15y5oyzm33c7/caffe2-prebuiltl.tar?dl=0
or see the latest README
hope ie helps

**Comment by twerdster** [comment]
Thanks,
this solved the issue

**Comment by lamia482** [comment]
uhm…   It may meet some errors， I'll try reupload later


> 在 2017年11月30日，下午5:19，Aaron Wetzler <notifications@github.com> 写道：
> 
> Thanks,
> this solved the issue
>

**Comment by twerdster** [comment]
Okay, thanks!
